[package]
	name = "winconsole"
	version = "0.5.0"
	authors = ["Omar M. <omarkmu@gmail.com>"]
	description = "A wrapper for console-related functions in the Windows API."
	license = "MIT OR Apache-2.0"
	readme = "README.md"
	repository = "https://github.com/omarkmu/winconsole"
	[package.metadata.docs.rs]
		features = ["input"]
		default-target = "x86_64-pc-windows-msvc"

[features]
	default = []
	input = []

[dependencies]
	lazy_static = "1.0"
	rgb = "0.8"
	[dependencies.serde]
		version = "1.0"
		features = ["serde_derive"]
		optional = true
	[dependencies.winapi]
		version = "0.3"
		features = [
			"consoleapi",
			"minwindef",
			"processenv",
			"utilapiset",
			"winbase",
			"wincon",
			"winnls",
			"winnt",
			"winuser"
		]

[target.'cfg(not(feature="serde"))'.dependencies]
	cgmath = "0.16"
[target.'cfg(feature="serde")'.dependencies]
	cgmath = { version = "0.16", features = ["serde"] }
